### ISSUE TITLE
Windows 系统下文件命名问题

### ISSUE THREAD

**Issue by love98ooo** [nuster1128/bilibiliAudioDownloader#9]
在Windows系统中，文件的命名不允许出现一些特殊字符，报错如下：
```
>python run.py -c BV1P24y1a7Lt
Downloader Start! ['BV1P24y1a7Lt']
Traceback (most recent call last):
  File "F:\Project\bilibiliAudioDownloader\run.py", line 81, in getAudioAndPic
    urllib.request.urlretrieve(url=audioUrl, filename='download/'+title+'.mp3')
  File "D:\Program Files\Python\Python311\Lib\urllib\request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
          ^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'download/【原神新春会】我不曾忘记 | 致旅行中的你.mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Project\bilibiliAudioDownloader\run.py", line 115, in <module>
    getAudioAndPic(getInformation(BVList))
  File "F:\Project\bilibiliAudioDownloader\run.py", line 85, in getAudioAndPic
    except (HTTPError, URLError, ContentTooShortError, OSError) as e:
            ^^^^^^^^^
NameError: name 'HTTPError' is not defined. Did you mean: 'TabError'?
```
我又看到相关对于特殊字符处理的代码
>
但是处理地不全面
解决办法：
```
import re

title = re.sub(r'[\/:*?"<>|]', " ", title)
```

**Comment by love98ooo** [comment]
#10
